[package]
name = "L3MOEXLOB"
version = "0.1.0"
edition = "2021"
authors = ["Artemy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.166", features = ["derive"]}
serde_json = "1.0.100"
tqdm = "0.5.0"