name: Build LaTeX Materials (July 2023)
on:   
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile presentation
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: Conference 2023 Materials/presentation/
          root_file: presentation.tex

      - name: Upload presentation
        uses: actions/upload-artifact@v3
        with:
          name: Presentation
          path: Conference 2023 Materials/presentation/presentation.pdf

      - name: Compile poster
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: Conference 2023 Materials/poster/
          root_file: poster.tex

      - name: Upload poster
        uses: actions/upload-artifact@v3
        with:
          name: Poster
          path: Conference 2023 Materials/poster/poster.pdf

      - name: Compile report
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: Conference 2023 Materials/report/
          root_file: document.tex

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: Conference 2023 Materials/report/document.pdf